"""segqc.reference — reference-distribution schema & per-level aggregation
core (Stage 6, item 043).

Pure ``records -> distributions`` aggregation: no file I/O, no VerSe/NiBabel
coupling. NumPy is the only heavy dependency (used solely to compute
statistics; results are stored as builtin ``float``).
"""

from .aggregate import aggregate_reference
from .delta import (
    DEFAULT_LOWER_PCT,
    DEFAULT_UPPER_PCT,
    INTENSITY_FEATURE_PREFIX,
    IQR_TO_SIGMA,
    REFERENCE_DELTA_VERSION,
    FeatureDelta,
    LabelDelta,
    ReferenceDelta,
    compute_intensity_reference_delta,
    compute_reference_delta,
    reference_delta_to_dict,
)
from .artifact import (
    ARTIFACT_SCHEMA_VERSION,
    DEFAULT_ARTIFACT_NAME,
    DEFAULT_BUILD_DATE,
    DEFAULT_SOURCE,
    ReferenceArtifactError,
    build_and_write_default,
    build_default_cohort,
    build_reference,
    bundled_default_reference,
    config_hash,
    default_artifact_path,
    load_artifact,
    write_artifact,
)
from .ingest import (
    DEFAULT_SCAN_SUFFIX,
    DEFAULT_SEG_SUFFIX,
    INGESTED_FEATURES,
    SIZE_PROXY_NAME,
    CohortIngest,
    SubjectIngest,
    ingest_cohort,
    ingest_subject,
)
from .schema import (
    ALL_STRATUM,
    DEFAULT_PERCENTILES,
    SCHEMA_VERSION,
    FeatureRecord,
    FeatureStats,
    LevelDistribution,
    Provenance,
    ReferenceDistribution,
    from_dict,
    to_dict,
    to_json_text,
)

__all__ = [
    "SCHEMA_VERSION",
    "DEFAULT_PERCENTILES",
    "ALL_STRATUM",
    "FeatureRecord",
    "Provenance",
    "FeatureStats",
    "LevelDistribution",
    "ReferenceDistribution",
    "aggregate_reference",
    "to_dict",
    "from_dict",
    "to_json_text",
    "DEFAULT_SEG_SUFFIX",
    "DEFAULT_SCAN_SUFFIX",
    "SIZE_PROXY_NAME",
    "INGESTED_FEATURES",
    "SubjectIngest",
    "CohortIngest",
    "ingest_subject",
    "ingest_cohort",
    "ARTIFACT_SCHEMA_VERSION",
    "DEFAULT_ARTIFACT_NAME",
    "DEFAULT_SOURCE",
    "DEFAULT_BUILD_DATE",
    "ReferenceArtifactError",
    "config_hash",
    "build_reference",
    "write_artifact",
    "load_artifact",
    "default_artifact_path",
    "bundled_default_reference",
    "build_default_cohort",
    "build_and_write_default",
    "REFERENCE_DELTA_VERSION",
    "DEFAULT_LOWER_PCT",
    "DEFAULT_UPPER_PCT",
    "IQR_TO_SIGMA",
    "INTENSITY_FEATURE_PREFIX",
    "FeatureDelta",
    "LabelDelta",
    "ReferenceDelta",
    "compute_reference_delta",
    "compute_intensity_reference_delta",
    "reference_delta_to_dict",
]
