"""Generated companion for the golden decision table's evidence cells (item
134; Stage 29, G7).

`docs/aide/golden-decision-table.md` is a human-signed document (item 105).
Nine of its Section-1 rows used to carry a live measurement --
`26/94 leaf paths unwired` -- transcribed by hand into signed text every time
a feature-adding item shifted the count (five such amendments before this
item; see the item spec's Description). That measurement is mechanical, not a
judgement, so it does not belong in signed text.

This module measures it instead and writes the result to a committed
companion, `docs/aide/golden_evidence.generated.json`; the signed document now
carries a digit-free pointer at that path rather than a number.

Scope fence: this module *measures*. It decides nothing about disposition,
rationale or replacement guarantees -- those stay in the signed document,
untouched by anything here.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional, Sequence

__all__ = ["build_evidence", "render_json", "main"]

_REPO_ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_PATH = _REPO_ROOT / "docs" / "aide" / "golden_evidence.generated.json"

SCHEMA_VERSION = "1.0"

_NOTE = (
    "Generated by `python -m segfacet.golden_evidence` -- do not hand-edit. "
    "Consumed by docs/aide/golden-decision-table.md's Section-1 evidence "
    "cells."
)


def build_evidence() -> Dict[str, Any]:
    """Measure, per corpus case, the total and unwired leaf-path counts.

    Builds the feature/rule catalogue once, then for every case in
    :func:`segfacet.synth.corpus.load_manifest`'s ``"cases"`` list computes
    the leaf-path set of :func:`segfacet.synth.golden.build_report_for_case`
    (case)["features"]`` via :func:`segfacet.catalogue.iter_leaf_paths`, and
    counts how many of those paths the catalogue marks ``"unwired"``. Pure:
    reads committed corpus/catalogue state, mutates nothing importable, and
    two calls in one session return equal payloads.
    """
    import segfacet.catalogue as catalogue
    from segfacet.synth.corpus import load_manifest
    from segfacet.synth.golden import build_report_for_case

    cat = catalogue.build_catalogue()
    status_by_path = {entry.path: entry.status for entry in cat.entries}

    manifest = load_manifest()
    cases: Dict[str, Dict[str, int]] = {}
    for case in manifest["cases"]:
        case_id = case["case_id"]
        report = build_report_for_case(case)
        leaf_paths = catalogue.iter_leaf_paths(report["features"])
        total_leaf_paths = len(leaf_paths)
        unwired_leaf_paths = sum(
            1 for p in leaf_paths if status_by_path.get(p) == "unwired"
        )
        cases[case_id] = {
            "total_leaf_paths": total_leaf_paths,
            "unwired_leaf_paths": unwired_leaf_paths,
        }

    return {
        "schema_version": SCHEMA_VERSION,
        "note": _NOTE,
        "cases": cases,
    }


def render_json(payload: Dict[str, Any]) -> str:
    """Render *payload* as the companion's committed JSON text.

    ``json.dumps(..., indent=2, sort_keys=True, ensure_ascii=False)`` plus a
    single trailing newline -- the house shape :mod:`segfacet.catalogue`
    already sets for a committed ``docs/aide/*.generated.*`` artifact.
    """
    import json

    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> int:
    """``python -m segfacet.golden_evidence [--out PATH]`` -- regenerate the
    committed companion (default: :data:`EVIDENCE_PATH`)."""
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Regenerate the golden decision table's evidence companion "
            "(item 134)."
        )
    )
    parser.add_argument("--out", type=Path, default=EVIDENCE_PATH)
    args = parser.parse_args(argv)

    payload = build_evidence()
    text = render_json(payload)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(text.encode("utf-8"))
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
